# CI environment

# Remote shutdown enabled
endpoints:
  shutdown:
    enabled: true

# Ontrack configuration
ontrack:
  config:
    # Disabling the test of the external configurations
    configuration-test: false
    # Integration with InfluxDB for the metrics
    metrics-period: 5
  metrics:
    influxdb:
      # The host is defined by the Docker link ontrack -> influxdb
      # Using the default internal port because of the link
      host: influxdb
      # Increases the refresh period for test
      period: 5
