---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
    component: "web"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      environment: {{ .Values.environment }}
      component: "web"
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        environment: {{ .Values.environment }}
        component: "web"
    spec:
      volumes:
        - name: {{ .Values.app.name }}-{{ .Values.environment }}-tmp-storage
          emptyDir: {}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.container.env.spring.datasource.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: doadmin
            - name: SPRING_DATASOURCE_PASSWORD
              value: mslp7sgti494j9zz
          volumeMounts:
            - mountPath: /var/ontrack/data
              name: {{ .Values.app.name }}-{{ .Values.environment }}-tmp-storage
          ports:
            - containerPort: {{ .Values.container.port }}
              name: {{ .Values.app.name }}-port
              protocol: TCP
