apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ontrack.fullname" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "ontrack.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.app.component }}"
type: Opaque
data:
  ontrack-spring-datasource-username: {{ .Values.container.env.spring.datasource.username | b64enc | quote }}
  ontrack-spring-datasource-password: {{ .Values.container.env.spring.datasource.password | b64enc | quote }}
