---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ontrack.fullname" . }}
  labels:
    "app.kubernetes.io/name": '{{ template "ontrack.name" .}}'
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.app.component }}"
spec:
  selector:
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": "{{ .Values.app.component }}"
  type: {{ .Values.app.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.container.port }}
      name: http
