---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
    component: "web"
spec:
  selector:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment }}
    component: "web"
  type: {{ .Values.app.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.container.port }}
      name: http
