version: "2.1"

services:

  postgresql:
    image: postgres:9.5.5
    container_name: "${POSTGRES_NAME:-postgresql}"
    environment:
      POSTGRES_DB: ontrack
      POSTGRES_USER: ontrack
      POSTGRES_PASSWORD: ontrack
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  # Vault
  # Non production setup
  # See https://hub.docker.com/_/vault/
  vault:
    image: "vault:1.3.2"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
    cap_add:
      - "IPC_LOCK"
    ports:
      - "8200:8200"

  keycloak:
    image: quay.io/keycloak/keycloak:10.0.0
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - 8008:8080
