version: "2.1"

services:

  postgresql:
    image: postgres:11
    container_name: "${POSTGRES_NAME:-postgresql}"
    environment:
      POSTGRES_DB: ontrack
      POSTGRES_USER: ontrack
      POSTGRES_PASSWORD: ontrack
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  influxdb:
    image: influxdb:1.8.6
    ports:
      - "8086:8086"

  # Vault
  # Non production setup
  # See https://hub.docker.com/_/vault/
  vault:
    image: "vault:1.3.2"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
    cap_add:
      - "IPC_LOCK"
    ports:
      - "8200:8200"

  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - 8008:8080

  # Rabbit MQ
  rabbit:
    image: rabbitmq:3.8.25-management
    restart: always
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ontrack
      RABBITMQ_DEFAULT_PASS: ontrack
    ports:
      - "15672:15672"
      - "5672:5672"
