version: "2"

services:

  # Database
  postgres:
    image: postgres:9.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack

  # InfluxDB container
  influxdb:
    image: influxdb:1.1-alpine
    environment:
      PRE_CREATE_DB: "ontrack"
    # Makes all ports accessible on the host for testing
    ports:
      - "8086:8086"
