# Application properties

# Spring configuration
spring:
  # Default database connection
  datasource:
    url: "jdbc:postgresql://localhost/ontrack"
    username: ontrack
    password: ontrack
  # Default profile
  profiles:
    active: prod

# Compression of web resources
server:
  compression:
    enabled: true

# Management
management:
  # Listening on a specific port
  server:
    port: 8800
  # Custom URL for the management end points and definition of exposure
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: "/manage"
  # Default settings for the metrics
  metrics:
    export:
      # InfluxDB disabled by default
      influx:
        enabled: false
      # Prometheus disabled by default
      prometheus:
        enabled: false
  # Health indicators
  health:
    # Disable LDAP health indicator
    ldap:
      enabled: false
    # Disable the ElasticSearch health indicator by default
    elasticsearch:
      enabled: false

# The version information is generated in /config/application.properties by the build
info:
  app:
    name: Ontrack
    description: Continuous Delivery Traceability and Monitoring

# Session configuration
# This can be overridden at installation level
#server:
#  session:
#    # One hour for the session
#    timeout: 3600
#    cookie:
#      max-age: 3600

okta:
  oauth2:
    issuer: "https://dev-991108.okta.com/oauth2/default"
    client-id: "0oa3prwngqXvuHmcJ357"
    client-secret: "Ym7SFacOkH9ARisax5IpqVXhiW4m9GnFs6pRHV2J"
