# ID for the resources
# Defaults to the Chart Name
# See templates/_helpers.tpl
# nameOverride:

# Namespace used for the deployment of resources
# Defaults to the Release Namespace
# See templates/_helpers.tpl
# namespaceOverride:

app:
  name: ontrack
  component: web
  service:
    type: LoadBalancer
    port: 80
replicas: 1
container:
  image: nemerosa/ontrack
  tag: 3.38.2
  port: 8080

  healthProbesPath: /manage/health

  healthProbesLivenessTimeout: 5
  healthProbeLivenessPeriodSeconds: 10
  healthProbeLivenessFailureThreshold: 5
  healthProbeLivenessInitialDelay: 300

  healthProbesReadinessTimeout: 5
  healthProbeReadinessPeriodSeconds: 10
  healthProbeReadinessFailureThreshold: 3
  healthProbeReadinessInitialDelay: 60

  env:
    vault:
      uri:
      token:
    spring:
      datasource:
        url: "jdbc:postgresql://postgres:5432/ontrack"
        username: ontrack
        password: ontrack
