version: "2.1"

services:
   postgres:
    image: postgres:11
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
      ports:
         - "9200:9200"
         - "9300:9300"
      environment:
         - "discovery.type=single-node"
   ontrack:
      build:
        context: "./os/debian/docker"
      tty: true
      command: "/bin/cat"
      environment:
         SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres/ontrack"
         SPRING_ELASTICSEARCH_URIS: "http://elasticsearch:9200"
      depends_on:
         postgres:
            condition: service_started
         elasticsearch:
            condition: service_started
   selenium:
      image: "selenium/standalone-chrome:3.11.0"
      environment:
         JAVA_OPTS: "-Xmx3072m -Xms3072m"
   ontrack_acceptance:
      image: "nemerosa/ontrack-acceptance:${VERSION:-latest}"
      depends_on:
         ontrack:
            condition: service_started
         selenium:
            condition: service_started
      environment:
         ONTRACK_ACCEPTANCE_IMPLICIT_WAIT: 30
         ONTRACK_ACCEPTANCE_SELENIUM_GRID_URL: http://selenium:4444/wd/hub
         ONTRACK_ACCEPTANCE_SELENIUM_BROWSER_NAME: chrome
         ONTRACK_ACCEPTANCE_SELENIUM_TARGET_URL: http://ontrack:8080
         ONTRACK_ACCEPTANCE_TARGET_URL: http://ontrack:8080
         ONTRACK_ACCEPTANCE_CONTEXT: smoke
         JAVA_OPTIONS: "-Xmx2048m -Xms2048m"
      volumes:
         - "./build:/ontrack/acceptance/output:rw"
